Пользовательские валидаторы в django работают только после встроенного валидатора cleaned_data. Только после него создаётся словарь, со значениями которого можно работать и уже их можно валидировать пользовательским валидатором.

Пользовательские валидаторы запускаются автоматически при вызове метода is_valid().
Django делает:
- Проверку, что данные переданы (POST, FILES)
- Запуск встроенной и кастомной валидации:
- у модели (validators=[...])
- в форме (clean_<field>())
- в clean() (общая валидация всей формы)
- у типов полей (CharField, EmailField и др.)
И если что-то не прошло — создаётся form.errors


